version: "3"
services:
    react:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        container_name: react
networks:
    internal:
        driver: bridge
